trigger:
  branches:
    include:
    - master
    - ci/*
    - bug/*
    - feature/*

stages:
- stage: Build

  jobs:
  - job: Build
    pool:
      vmImage: 'macOS-latest'
      #name: MacOS-private
      demands: msbuild

    steps:
    - bash: |
        echo "##vso[build.updatebuildnumber]$(major).$(minor).$(Build.BuildId)"
      name: SetBuildName

    - task: PowerShell@2
      displayName: 'PowerShell Script - update version number in project files'
      inputs:
        targetType: filePath
        arguments: "-version '$(Build.BuildNumber)'"
        filePath: './.build/UpdateVersion.ps1'

    - task: NuGetCommand@2
      inputs:
        command: 'restore'

    - task: MSBuild@1
      displayName: 'Build solution **/*.sln'
      inputs:
        platform: '$(BuildPlatform)'
        configuration: '$(BuildConfiguration)'

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
      inputs:
        SourceFolder: '$(build.sourcesdirectory)'
        Contents: '**/bin/$(BuildConfiguration)/**'
        TargetFolder: '$(build.artifactstagingdirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'

- template: /.azuredevops/templates/stages-sync-with-github.yaml
  parameters:
    repository: CopyWordsXN